---
- name: Pré-instalação do Docker
  apt:
    name:
      - ca-certificates
      - curl
    update_cache: yes

- name: Permissões de pasta Key
  shell: install -m 0755 -d /etc/apt/keyrings

- name: Adicionar chave GPG ao repositório
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc

- name: Adicionar repo Docker ao sources
  apt_repository: 
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Permissão de leitura à chave
  shell: chmod a+r /etc/apt/keyrings/docker.asc

- name: Instalação do Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: yes

- name: Adicionando grupo docker
  group:
    name: docker
    state: present
    
- name: Adicionando usuário ao grupo docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Ativar e iniciar os serviços docker
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - docker.service
    - containerd.service